### ISSUE TITLE
What is the purpose of the "internal" sub-library?

### ISSUE THREAD

**Issue by peti** [dmjio/s3-signer#11]
I am very confused by the definition of the sublibrary called "internal". What is it's purpose? It looks almost identical to the proper library defined in this package.

**Comment by dmjio** [comment]
I was curious as well, maybe @jb55 can speak to this. If we don’t need it I’m ok removing it.

**Comment by jb55** [comment]
David Johnson <notifications@github.com> writes:
> I was curious as well, maybe @jb55 can speak to this. If we don’t need it I’m ok removing it.

yeah I don't remember why I did this, feel free to remove.

**Comment by dmjio** [comment]
Removed in `0.5.0.0`. It seems the internal library was solely a convenience that let us bypass specifying the modules and dependencies twice in the `test-suite`.

**Comment by peti** [comment]
Why don't you just make the test suite depend on the `s3-signer` library?

**Comment by dmjio** [comment]
The test suite relies on modules that the library does not expose.
